### ISSUE TITLE
use vite instead of creact-react-app

### ISSUE THREAD

**Issue by alioguzhan** [teloscube/create-decaf-webapp#14]
## CRA

https://create-react-app.dev/

- They almost stopped maintaining the `create-react-app`.  (last commit was [8 months ago](https://github.com/facebook/create-react-app))
- It's been months since Typescript 5 was released, but it still doesn't support it. 
    - You need to override the typescript version to make it work (as we are doing now)
-  They don't even recommend it [on the React website](https://react.dev/learn/start-a-new-react-project) (In fact, Vite is now recommended along with the Parcel)

## Vite

https://vitejs.dev/

- It is way faster
- Actively maintained
- Recommended by React
- No lock-in. Can be extended freely with plugins and configs
- Fast
- Fast
- Did I say it is fast?

![image](https://github.com/teloscube/create-decaf-webapp/assets/1928541/c667e82b-10e8-45a1-b1b7-6038e170244b)

I will investigate what our options to keep our magnificent deployment flow working while migrating to Vite. 

@vst @fkoksal

**Comment by alioguzhan** [comment]
UPDATE: There is this. It is open since 2021. Looks suspicious. 

https://github.com/vitejs/vite/issues/2433

**Comment by fkoksal** [comment]
> UPDATE: There is this. It is open since 2021. Looks suspicious.
> 
> [vitejs/vite#2433](https://github.com/vitejs/vite/issues/2433)

If it's only related to building stage, I think we can live with it. Or?

**Comment by alioguzhan** [comment]
Yes. Only for the building stage. We may encounter some problems on Github Actions though. I am not sure about the memory limits for those machines.

**Comment by vst** [comment]
Let's discuss this.

**Comment by alioguzhan** [comment]
Done with #15
