### ISSUE TITLE
Can we have import aliases setup?

### ISSUE THREAD

**Issue by vst** [teloscube/create-decaf-webapp#25]
**Is your feature request related to a problem? Please describe.**

It is rather a DX improvement.

**Describe the solution you'd like**

I would like to be able to import as follows:

```ts
import { hebele } from '@/autogen/hubele';
import { hebele } from '@/components/hubele';
import { hebele } from '@/lib/hubele';
import { hebele } from '@/pages/hubele';
```

**Describe alternatives you've considered**

`#N/A`

**Additional context**

Something like this: https://nextjs.org/docs/app/building-your-application/configuring/absolute-imports-and-module-aliases

**Comment by alioguzhan** [comment]
Done with 3984738e6c18a79dd45b252e23030883a8151ee1
